# Generated by Django 3.2 on 2022-10-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
